### ISSUE TITLE
APIExperiment.get_asset JSONDecodeError

### ISSUE THREAD

**Issue by kdmcdrm** [comet-ml/issue-tracking#209]
Hey, not sure if I'm doing something wrong here but I'm getting a JSONDecodeError when I try to get an asset from my experiment. Can you only request JSON objects? My asset is a pickle file.

In case it's needed, I ran this with requests library at 2.20.1 and 2.21.0.

Snippet: 
``` python
exp.get_asset(ASSET_KEY)

Traceback (most recent call last):
  File "<ENV_PATH>/lib/python3.6/site-packages/comet_ml/api.py", line 273, in get_asset
    return self._api.get_experiment_asset(self.key, asset_id)
  File "<ENV_PATH>/lib/python3.6/site-packages/comet_ml/api.py", line 924, in get_experiment_asset
    results = self.get_request("asset/get-asset", params)
  File "<ENV_PATH>/lib/python3.6/site-packages/comet_ml/api.py", line 673, in get_request
    return response.json()
  File "<ENV_PATH>/lib/python3.6/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "<ENV_PATH>/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "<ENV_PATH>/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "<ENV_PATH>/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by dsblank** [comment]
Thanks for reporting this. It looks like an encoding error on our end. I will explore it.

**Comment by dsblank** [comment]
Yep, that was our problem. Fixed and will be released in next version of the Python SDK (should be released soon). Will report back here and close when released. Thanks again!

**Comment by Nimrod007** [comment]
updated on  `comet-ml 1.0.45`
