### ISSUE TITLE
Error when uploading Experiment to comet.ml 

### ISSUE THREAD

**Issue by ishouldbedany** [comet-ml/issue-tracking#25]
I am getting a connection error when uploading my experiment to comet.ml. Minimal working example below: 

```
from comet_ml import Experiment
experiment = Experiment(api_key="my_api_key", project_name="my_project_name", team_name="my_team_name", log_code=False)

# (data loading)

# Setting up hyperparameter grid
param_grid =  {'n_estimators': [10, 50, 100, 500, 1000],
                'max_features': [5, 15, 50],
                'max_depth': [1, 3, 5],
                'min_samples_split': [2, 10]
                }


# Setting up the searcher
clf = RandomForestClassifier(random_state=52)
searcher = RandomizedSearchCV(clf, param_grid, scoring=['accuracy', 'precision', 'recall', 'f1'], cv=N_FOLDS, refit='f1', verbose=True, n_jobs=-1) # f1 is the decision scorer
searcher.fit(train_data_win, train_labels_win)
```

I am always getting back the following error: 

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/comet_ml/__init__.py", line 296, in _authenticate
    self.project_name, self.team_name
  File "/usr/local/lib/python3.6/site-packages/comet_ml/connection.py", line 140, in get_run_id
    raise ValueError(r.content)
ValueError: b'{"msg":"unexpected error","version":"9beed354d5345e881864ad8f3d7e527d73795dca","code":500,"data":null}'
 
 Failed to establish connection to Comet server. Please check your internet connection. Your experiment would not be logged

```

Does it have something to do with the use of `RandomizedSearchCV` or `GridSearchCV`? Thanks!

**Comment by ishouldbedany** [comment]
Sorry, I forgot about the first imports, but both `RandomForestClassifier` and `RandomizedSearchCV` are coming from `scikit-learn`.

**Comment by Nimrod007** [comment]
perfect ! thanks

**Comment by Nimrod007** [comment]
closing for now. @ishouldbedany - please re-open if needed

**Comment by ishouldbedany** [comment]
@Nimrod007 Sorry, I no longer have the exact code to reproduce this. I have been, however, doing several other experiments with `sklearn`'s `GridSearchCV` (but not `RandomizedSearchCV`) and have not ran into any issue. Thanks!
