### ISSUE TITLE
Error message: ``an integer is required (got type str)'' when using a proxy (fix included.)

### ISSUE THREAD

**Issue by shawntan** [comet-ml/issue-tracking#288]
Logs with DEBUG:
```
[43052-MainProcess:47967072491264] 2383 COMET DEBUG [connection.py:891]: Using HTTPS_PROXY: localhost:8888
[43052-MainProcess:47967072491264] 2384 COMET DEBUG [connection.py:408]: Report notify URL: https://www.comet.ml/clientlib/notify/event
[43052-MainProcess:47967072491264] 2630 COMET DEBUG [connection.py:794]: WS on error: TypeError('an integer is required (got type str)')
Traceback (most recent call last):
  File "/home/shawntan/.local/lib/python3.7/site-packages/websocket/_app.py", line 254, in run_forever
    proxy_type=proxy_type)
  File "/home/shawntan/.local/lib/python3.7/site-packages/websocket/_core.py", line 223, in connect
    options.pop('socket', None))
  File "/home/shawntan/.local/lib/python3.7/site-packages/websocket/_http.py", line 105, in connect
    return _open_proxied_socket(url, options, proxy)
  File "/home/shawntan/.local/lib/python3.7/site-packages/websocket/_http.py", line 91, in _open_proxied_socket
    socket_options = DEFAULT_SOCKET_OPTION + options.sockopt
  File "/home/shawntan/anaconda3/lib/python3.7/site-packages/socks.py", line 252, in create_connection
    sock.connect((remote_host, remote_port))
  File "/home/shawntan/anaconda3/lib/python3.7/site-packages/socks.py", line 100, in wrapper
    return function(*args, **kwargs)
  File "/home/shawntan/anaconda3/lib/python3.7/site-packages/socks.py", line 832, in connect
    super(socksocket, self).connect(proxy_addr)
TypeError: an integer is required (got type str)
```

Changing line `882`
```python
http_proxy_port = str(http_proxy_obj.port)
```
to 
```python
http_proxy_port = int(http_proxy_obj.port)
```
fixed it for me.

**Comment by dsblank** [comment]
Thanks! Look for a fix in a released version soon.

**Comment by dsblank** [comment]
@shawntan You should find comet_ml version 2.0.9 fixes this issue. Thanks for the hints!

**Comment by shawntan** [comment]
That was fast! Thanks!
