### ISSUE TITLE
Using Comet.ML in the multi-GPU environment with torch.multiprocessing fails

### ISSUE THREAD

**Issue by sdll** [comet-ml/issue-tracking#313]
## Issue

I am integrating comet.ml into the [FAIRSEQ training script](https://github.com/phramer/fairseq/blob/245986d07fb730085244afbfdd3252de4c4c3cd4/train.py) and having troubles wrapping my head around the Experiment object in the torch.multiprocessing environment.

Could you please tell me how you would approach initializing the Experiment object once, and then passing it to the processes? 

[Passing it as an argument to the parallelized function](https://github.com/phramer/fairseq/blob/245986d07fb730085244afbfdd3252de4c4c3cd4/train.py#L367) fails with the following error:

![IMAGE 2019-11-08 21:40:23](https://user-images.githubusercontent.com/17913919/68501927-60180100-0270-11ea-97d9-f1d8ab6e93f3.jpg)

## Environment
- Ubuntu 18.04.3 LTS
- Python 3.6.8
- comet_ml 2.0.17
- torch 1.2.0

## Related Issues

https://github.com/comet-ml/issue-tracking/issues/202

**Comment by dsblank** [comment]
@sdll You might want to think about using an `ExistingExperiment()` object in each process rather than a shared `Experiment()` across processes. You might also want to look at how we handled this in the `comet optimizer` command line: see comet_ml/scripts/comet_optimize.py

**Comment by sdll** [comment]
@dsblank, thanks! Is there a better way to look at the Python SDK source code other than peeking into the comet_ml tar.gz from pypi?

**Comment by awlego** [comment]
I'm using the `ExistingExperiment()` in the one process I have flagged to do the logging, and things seem to mostly work except comet always prints `COMET INFO: Still uploading` at the end of the run for several minutes and then warns that there may be missing data.
```COMET INFO: Still uploading
COMET INFO: Still uploading
... 
COMET INFO: Still uploading
COMET WARNING: Failed to send all messages, metrics and output will likely be incomplete
COMET ERROR: Comet failed to send all the data back (50 messages and 0 uploads)
COMET WARNING: Failed to log run in comet.ml
```
I've also had to set `auto_output_logging='simple'` in order to not have an io error. Any idea on this comet warning/error? No other comet warnings/errors are printed until the upload error at the very end.

**Comment by dsblank** [comment]
@awlego We are looking into this issue.

**Comment by dsblank** [comment]
> Is there a better way to look at the Python SDK source code other than peeking into the comet_ml tar.gz from pypi?

@sdll When you pip install the comet_ml package you get the source code. On many Linux systems, you can `locate comet_ml/scripts/comet_optimize.py` to find any files by that name. There are probably other ways to find a particular file on a system as well.

**Comment by dsblank** [comment]
@awlego A workaround: if you put `experiment.end()` at the end of the run, this finishes the uploads for the experiment, before starting the next one. But we are working on a fix...

**Comment by dsblank** [comment]
Now testing fix...

**Comment by dsblank** [comment]
@sdll Please try comet_ml version 2.0.18 (or greater). We think that this should address the issue.

**Comment by awlego** [comment]
Thanks for working on the fix! I appreciate it.

With comet_ml version 2.0.18 I hit my system open file limit after about an hour of training (`$ ulimit -n`: `4096`). Reverting to 2.0.17 with no other changes to anything in the data/training/etc works just fine.

Of note this test was with my old workaround of passing `auto_output_logging=None` to both the experiment creation and the `ExistingExperiment` creation. I will be running tests with the default operation shortly.

**Comment by awlego** [comment]
Unfortunately it 2.0.18 also errors with the default settings for me.

```Process Process-1:1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kuna/alex/repositories/detectron2/env3/lib/python3.6/site-packages/comet_ml/console.py", line 121, in _tee_process
    r, _, _ = select.select(pipes, [], [], 0.1)
OSError: [Errno 9] Bad file descriptor```

It looks like it might be an error with the subprocess not being able to read the text printed to the terminal. Unfortunately the work around of `auto_output_logging=None` also suppresses GPU utilization tracking, but it does seem to at least let me train with manual metric tracking.

**Comment by dsblank** [comment]
There is also `auto_output_logging="simple"` ... that might help,

**Comment by dsblank** [comment]
Closing due to inactivity. Please feel free to reopen with more information.
