### ISSUE TITLE
Upload OfflineExperiment failing

### ISSUE THREAD

**Issue by murnanedaniel** [comet-ml/issue-tracking#322]
I am getting the following error when I try to upload an OfflineExperiment

```
python -m comet_ml.scripts.comet_upload 8530386ae84a48c9865e12c4e31519fe.zip 
COMET INFO: Attempting to upload '8530386ae84a48c9865e12c4e31519fe.zip'...
COMET ERROR:     Upload failed
Traceback (most recent call last):
  File "/global/homes/d/danieltm/.local/cori/pytorchv1.2.0-gpu/lib/python3.6/site-packages/comet_ml/offline.py", line 590, in main_upload
    filename, api_key, force_reupload
  File "/global/homes/d/danieltm/.local/cori/pytorchv1.2.0-gpu/lib/python3.6/site-packages/comet_ml/offline.py", line 561, in upload_single_offline_experiment
    sender = OfflineSender(api_key, unzipped_directory, force_reupload=force_reupload)
  File "/global/homes/d/danieltm/.local/cori/pytorchv1.2.0-gpu/lib/python3.6/site-packages/comet_ml/offline.py", line 362, in __init__
    self._read_experiment_file()
  File "/global/homes/d/danieltm/.local/cori/pytorchv1.2.0-gpu/lib/python3.6/site-packages/comet_ml/offline.py", line 388, in _read_experiment_file
    self.experiment_file_validator.validate(metadata)
  File "/usr/common/software/pytorch/v1.2.0-gpu/lib/python3.6/site-packages/jsonschema/validators.py", line 348, in validate
    raise error
jsonschema.exceptions.ValidationError: False is not of type 'string', 'null'

Failed validating 'type' in schema['properties']['auto_output_logging']:
    {'$id': '#/properties/auto_output_logging',
     'default': '',
     'enum': ['simple', 'native', None],
     'examples': ['native'],
     'pattern': '^(.*)$',
     'title': 'The Auto_output_logging Schema',
     'type': ['string', 'null']}

On instance['auto_output_logging']:
    False
COMET INFO: Number of uploaded experiments: 0
COMET INFO: Number of failed experiment uploads: 1
```

It's not clear to me how to avoid this issue.

**Comment by dsblank** [comment]
@murnanedaniel Do you have the output logs when you created the experiment? See: https://staging.comet.ml/docs/python-sdk/advanced/#troubleshooting

**Comment by murnanedaniel** [comment]
I'm using Jupyter, and this is sort of a side-track, but how do I set the debug file from within Jupyter? I've tried adding the path to .comet.config, as well as calling
```
os.environ['COMET_LOGGING_FILE'] = "log/debug.log"
os.environ['COMET_LOGGING_FILE_LEVEL'] = "debug"
```
but the file is not produced when I initialize a new `OfflineExperiment`. Once I can get this, I'll upload it.

**Comment by dsblank** [comment]
If you do the above before you import comet_ml, you should be good. (You have to make sure that the directory "./log" exists, I believe).
