### ISSUE TITLE
Comet fails in debug mode but successfully runs in Run mode. 

### ISSUE THREAD

**Issue by iulialexandra** [comet-ml/issue-tracking#330]
Hi, I am experiencing a strange error coming from Comet only when I enable debug mode in PyCharm:
RuntimeError: DataLoader worker (pid 15503) is killed by signal: Terminated. 
Python 3.7.6,  PyCharm 2018.1.2 (Professional Edition).

Why does this happen? 

Thanks,
Iulia

Error trace:
  File "/opt/pycharm-2018.1.2/helpers/pydev/pydevd.py", line 1664, in <module>
  File "/opt/pycharm-2018.1.2/helpers/pydev/pydevd.py", line 1664, in <module>
Traceback (most recent call last):
  File "/opt/pycharm-2018.1.2/helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/opt/pycharm-2018.1.2/helpers/pydev/pydevd.py", line 1658, in main
        main()main()

  File "/opt/pycharm-2018.1.2/helpers/pydev/pydevd.py", line 1658, in main
  File "/opt/pycharm-2018.1.2/helpers/pydev/pydevd.py", line 1658, in main
        globals = debugger.run(setup['file'], None, None, is_module)
  File "/opt/pycharm-2018.1.2/helpers/pydev/pydevd.py", line 1068, in run
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/opt/pycharm-2018.1.2/helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/opt/pycharm-2018.1.2/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/mnt/Storage/code/incremental/icarl_pytorch/main.py", line 140, in <module>
    pydev_imports.execfile(file, globals, locals)  # execute the script
    main()
  File "/opt/pycharm-2018.1.2/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
  File "/mnt/Storage/code/incremental/icarl_pytorch/main.py", line 88, in main
    num_epochs, inc_phase)
  File "/mnt/Storage/code/incremental/icarl_pytorch/model.py", line 191, in update_representation
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/mnt/Storage/code/incremental/icarl_pytorch/main.py", line 140, in <module>
    for i, (indices, images, labels) in enumerate(loader):
  File "/home/iulialexandra/anaconda3/envs/latest_torch/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 279, in __iter__
    main()
  File "/mnt/Storage/code/incremental/icarl_pytorch/main.py", line 88, in main
    return _MultiProcessingDataLoaderIter(self)
  File "/home/iulialexandra/anaconda3/envs/latest_torch/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 719, in __init__
    num_epochs, inc_phase)
  File "/mnt/Storage/code/incremental/icarl_pytorch/model.py", line 191, in update_representation
        w.start()
for i, (indices, images, labels) in enumerate(loader):  File "/home/iulialexandra/anaconda3/envs/latest_torch/lib/python3.7/multiprocessing/process.py", line 112, in start

  File "/home/iulialexandra/anaconda3/envs/latest_torch/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 279, in __iter__
    self._popen = self._Popen(self)
  File "/home/iulialexandra/anaconda3/envs/latest_torch/lib/python3.7/multiprocessing/context.py", line 223, in _Popen
    return _MultiProcessingDataLoaderIter(self)
  File "/home/iulialexandra/anaconda3/envs/latest_torch/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 719, in __init__
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/iulialexandra/anaconda3/envs/latest_torch/lib/python3.7/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/home/iulialexandra/anaconda3/envs/latest_torch/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/home/iulialexandra/anaconda3/envs/latest_torch/lib/python3.7/multiprocessing/popen_fork.py", line 70, in _launch
    self.pid = os.fork()
  File "/opt/pycharm-2018.1.2/helpers/pydev/_pydev_bundle/pydev_monkey.py", line 464, in new_fork
    w.start()
  File "/home/iulialexandra/anaconda3/envs/latest_torch/lib/python3.7/multiprocessing/process.py", line 112, in start
globals = debugger.run(setup['file'], None, None, is_module)    _on_forked_process()
  File "/opt/pycharm-2018.1.2/helpers/pydev/_pydev_bundle/pydev_monkey.py", line 50, in _on_forked_process
    self._popen = self._Popen(self)
  File "/home/iulialexandra/anaconda3/envs/latest_torch/lib/python3.7/multiprocessing/context.py", line 223, in _Popen
    pydevd.settrace_forked()
  File "/opt/pycharm-2018.1.2/helpers/pydev/pydevd.py", line 1445, in settrace_forked
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/iulialexandra/anaconda3/envs/latest_torch/lib/python3.7/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/home/iulialexandra/anaconda3/envs/latest_torch/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/home/iulialexandra/anaconda3/envs/latest_torch/lib/python3.7/multiprocessing/popen_fork.py", line 70, in _launch
    self.pid = os.fork()
  File "/opt/pycharm-2018.1.2/helpers/pydev/_pydev_bundle/pydev_monkey.py", line 464, in new_fork
    patch_multiprocessing=True,
  File "/opt/pycharm-2018.1.2/helpers/pydev/pydevd.py", line 1210, in settrace
    _on_forked_process()
  File "/opt/pycharm-2018.1.2/helpers/pydev/_pydev_bundle/pydev_monkey.py", line 50, in _on_forked_process
    pydevd.settrace_forked()
  File "/opt/pycharm-2018.1.2/helpers/pydev/pydevd.py", line 1445, in settrace_forked
    patch_multiprocessing,
  File "/opt/pycharm-2018.1.2/helpers/pydev/pydevd.py", line 1254, in _locked_settrace
    patch_multiprocessing=True,
  File "/opt/pycharm-2018.1.2/helpers/pydev/pydevd.py", line 1210, in settrace

  File "/opt/pycharm-2018.1.2/helpers/pydev/pydevd.py", line 1068, in run
    debugger.connect(host, port)  # Note: connect can raise error.
  File "/opt/pycharm-2018.1.2/helpers/pydev/pydevd.py", line 328, in connect
    patch_multiprocessing,
  File "/opt/pycharm-2018.1.2/helpers/pydev/pydevd.py", line 1254, in _locked_settrace
    self.initialize_network(s)
  File "/opt/pycharm-2018.1.2/helpers/pydev/pydevd.py", line 320, in initialize_network
    time.sleep(0.1)  # give threads time to start
KeyboardInterrupt
    debugger.connect(host, port)  # Note: connect can raise error.
  File "/opt/pycharm-2018.1.2/helpers/pydev/pydevd.py", line 328, in connect
    self.initialize_network(s)
  File "/opt/pycharm-2018.1.2/helpers/pydev/pydevd.py", line 320, in initialize_network
    time.sleep(0.1)  # give threads time to start
KeyboardInterrupt
COMET INFO: ----------------------------
COMET INFO: Comet.ml Experiment Summary:
COMET INFO:   Data:
COMET INFO:     url: https://www.comet.ml/iulialexandra/pytorch-icarl/7cef911d45fa46d49c3faeac4efdc540
COMET INFO:   Metrics [count] (min, max):
COMET INFO: ----------------------------
COMET INFO: Comet.ml Experiment Summary:
COMET INFO:     sys.cpu.percent.01       : (18.3, 18.3)
COMET INFO:   Data:
COMET INFO:     sys.cpu.percent.02       : (1.6, 1.6)
COMET INFO:     url: https://www.comet.ml/iulialexandra/pytorch-icarl/7cef911d45fa46d49c3faeac4efdc540
COMET INFO:     sys.cpu.percent.03       : (60.1, 60.1)
COMET INFO:   Metrics [count] (min, max):
COMET INFO:     sys.cpu.percent.04       : (4.9, 4.9)
COMET INFO:     sys.cpu.percent.05       : (6.9, 6.9)
COMET INFO:     sys.cpu.percent.01       : (18.3, 18.3)
    COMET INFO:     sys.cpu.percent.06       : (1.3, 1.3)
COMET INFO:     sys.cpu.percent.02       : (1.6, 1.6)
COMET INFO:     sys.cpu.percent.07       : (1.6, 1.6)
COMET INFO:     sys.cpu.percent.03       : (60.1, 60.1)
COMET INFO:     sys.cpu.percent.08       : (16.4, 16.4)
pydev_imports.execfile(file, globals, locals)  # execute the scriptCOMET INFO:     sys.cpu.percent.04       : (4.9, 4.9)
COMET INFO:     sys.cpu.percent.avg      : (13.8875, 13.8875)
COMET INFO:     sys.gpu.0.free_memory    : (11222384640.0, 11222384640.0)
COMET INFO:     sys.cpu.percent.05       : (6.9, 6.9)
COMET INFO:     sys.gpu.0.gpu_utilization: (1.0, 1.0)
COMET INFO:     sys.gpu.0.total_memory   : (11721506816.0, 11721506816.0)

COMET INFO:     sys.cpu.percent.06       : (1.3, 1.3)
COMET INFO:     sys.gpu.0.used_memory    : (499122176.0, 499122176.0)
COMET INFO:     sys.cpu.percent.07       : (1.6, 1.6)
COMET INFO:     sys.load.avg             : (1.04, 1.04)
COMET INFO:     sys.cpu.percent.08       : (16.4, 16.4)
COMET INFO:     sys.ram.total            : (33106694144.0, 33106694144.0)
  File "/opt/pycharm-2018.1.2/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
COMET INFO:     sys.cpu.percent.avg      : (13.8875, 13.8875)
COMET INFO:     sys.ram.used             : (6312587264.0, 6312587264.0)
COMET INFO:     sys.gpu.0.free_memory    : (11222384640.0, 11222384640.0)
COMET INFO:   Other [count]:
COMET INFO:     sys.gpu.0.gpu_utilization: (1.0, 1.0)
COMET INFO:     sys.gpu.0.total_memory   : (11721506816.0, 11721506816.0)
COMET INFO:     Name: 2020_2_13-17_9_52_146147_seed_0_1_epochs_2000_exemplars
COMET INFO:   Uploads:
COMET INFO:     sys.gpu.0.used_memory    : (499122176.0, 499122176.0)
COMET INFO:     git-patch  : 1
COMET INFO:     histogram3d: 1
COMET INFO:     sys.load.avg             : (1.04, 1.04)
COMET INFO:     sys.ram.total            : (33106694144.0, 33106694144.0)
COMET INFO: ----------------------------
COMET INFO:     sys.ram.used             : (6312587264.0, 6312587264.0)
COMET INFO:   Other [count]:
COMET INFO:     Name: 2020_2_13-17_9_52_146147_seed_0_1_epochs_2000_exemplars
COMET INFO:   Uploads:
    COMET INFO:     git-patch  : 1
COMET INFO:     histogram3d: 1
COMET INFO: ----------------------------
exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/mnt/Storage/code/incremental/icarl_pytorch/main.py", line 140, in <module>
    main()
  File "/mnt/Storage/code/incremental/icarl_pytorch/main.py", line 88, in main
    num_epochs, inc_phase)
  File "/mnt/Storage/code/incremental/icarl_pytorch/model.py", line 191, in update_representation
    for i, (indices, images, labels) in enumerate(loader):
  File "/home/iulialexandra/anaconda3/envs/latest_torch/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/iulialexandra/anaconda3/envs/latest_torch/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 841, in _next_data
    idx, data = self._get_data()
  File "/home/iulialexandra/anaconda3/envs/latest_torch/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 808, in _get_data
    success, data = self._try_get_data()
  File "/home/iulialexandra/anaconda3/envs/latest_torch/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 761, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/home/iulialexandra/anaconda3/envs/latest_torch/lib/python3.7/multiprocessing/queues.py", line 104, in get
    if not self._poll(timeout):
  File "/home/iulialexandra/anaconda3/envs/latest_torch/lib/python3.7/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/home/iulialexandra/anaconda3/envs/latest_torch/lib/python3.7/multiprocessing/connection.py", line 414, in _poll
    r = wait([self], timeout)
  File "/home/iulialexandra/anaconda3/envs/latest_torch/lib/python3.7/multiprocessing/connection.py", line 920, in wait
    ready = selector.select(timeout)
  File "/home/iulialexandra/anaconda3/envs/latest_torch/lib/python3.7/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt
COMET INFO: ----------------------------
COMET INFO: Comet.ml Experiment Summary:
COMET INFO:   Data:
COMET INFO:     url: https://www.comet.ml/iulialexandra/pytorch-icarl/7cef911d45fa46d49c3faeac4efdc540
COMET INFO:   Metrics [count] (min, max):
COMET INFO:     sys.cpu.percent.01       : (18.3, 18.3)
COMET INFO:     sys.cpu.percent.02       : (1.6, 1.6)
COMET INFO:     sys.cpu.percent.03       : (60.1, 60.1)
COMET INFO:     sys.cpu.percent.04       : (4.9, 4.9)
COMET INFO:     sys.cpu.percent.05       : (6.9, 6.9)
COMET INFO:     sys.cpu.percent.06       : (1.3, 1.3)
COMET INFO:     sys.cpu.percent.07       : (1.6, 1.6)
COMET INFO:     sys.cpu.percent.08       : (16.4, 16.4)
COMET INFO:     sys.cpu.percent.avg      : (13.8875, 13.8875)
COMET INFO:     sys.gpu.0.free_memory    : (11222384640.0, 11222384640.0)
COMET INFO:     sys.gpu.0.gpu_utilization: (1.0, 1.0)
COMET INFO:     sys.gpu.0.total_memory   : (11721506816.0, 11721506816.0)
COMET INFO:     sys.gpu.0.used_memory    : (499122176.0, 499122176.0)
COMET INFO:     sys.load.avg             : (1.04, 1.04)
COMET INFO:     sys.ram.total            : (33106694144.0, 33106694144.0)
COMET INFO:     sys.ram.used             : (6312587264.0, 6312587264.0)
COMET INFO:   Other [count]:
COMET INFO:     Name: 2020_2_13-17_9_52_146147_seed_0_1_epochs_2000_exemplars
COMET INFO:   Uploads:
COMET INFO:     git-patch  : 1
COMET INFO:     histogram3d: 1
COMET INFO: ----------------------------
COMET ERROR: Error sending notification, make sure you have opted-in for notifications
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/iulialexandra/anaconda3/envs/latest_torch/lib/python3.7/site-packages/comet_ml/__init__.py", line 348, in _on_end
    successful_clean = super(Experiment, self)._on_end(wait=wait)
  File "/home/iulialexandra/anaconda3/envs/latest_torch/lib/python3.7/site-packages/comet_ml/experiment.py", line 508, in _on_end
    self.logger.clean()
  File "/home/iulialexandra/anaconda3/envs/latest_torch/lib/python3.7/site-packages/comet_ml/console.py", line 414, in clean
    self.wrapper.__exit__(None, None, None)
  File "/home/iulialexandra/anaconda3/envs/latest_torch/lib/python3.7/site-packages/comet_ml/console.py", line 358, in __exit__
COMET ERROR: Error sending notification, make sure you have opted-in for notifications
    self.stdout_process.join(5)
  File "/home/iulialexandra/anaconda3/envs/latest_torch/lib/python3.7/multiprocessing/process.py", line 138, in join
    assert self._parent_pid == os.getpid(), 'can only join a child process'
AssertionError: can only join a child process
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/iulialexandra/anaconda3/envs/latest_torch/lib/python3.7/site-packages/comet_ml/__init__.py", line 348, in _on_end
    successful_clean = super(Experiment, self)._on_end(wait=wait)
  File "/home/iulialexandra/anaconda3/envs/latest_torch/lib/python3.7/site-packages/comet_ml/experiment.py", line 508, in _on_end
    self.logger.clean()
  File "/home/iulialexandra/anaconda3/envs/latest_torch/lib/python3.7/site-packages/comet_ml/console.py", line 414, in clean
    self.wrapper.__exit__(None, None, None)
  File "/home/iulialexandra/anaconda3/envs/latest_torch/lib/python3.7/site-packages/comet_ml/console.py", line 358, in __exit__
    self.stdout_process.join(5)
  File "/home/iulialexandra/anaconda3/envs/latest_torch/lib/python3.7/multiprocessing/process.py", line 138, in join
    assert self._parent_pid == os.getpid(), 'can only join a child process'
AssertionError: can only join a child process
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/iulialexandra/anaconda3/envs/latest_torch/lib/python3.7/multiprocessing/util.py", line 334, in _exit_function
    p.join()
  File "/home/iulialexandra/anaconda3/envs/latest_torch/lib/python3.7/multiprocessing/process.py", line 138, in join
    assert self._parent_pid == os.getpid(), 'can only join a child process'
AssertionError: can only join a child process
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/iulialexandra/anaconda3/envs/latest_torch/lib/python3.7/site-packages/comet_ml/__init__.py", line 348, in _on_end
    successful_clean = super(Experiment, self)._on_end(wait=wait)
  File "/home/iulialexandra/anaconda3/envs/latest_torch/lib/python3.7/site-packages/comet_ml/experiment.py", line 508, in _on_end
    self.logger.clean()
  File "/home/iulialexandra/anaconda3/envs/latest_torch/lib/python3.7/site-packages/comet_ml/console.py", line 414, in clean
    self.wrapper.__exit__(None, None, None)
  File "/home/iulialexandra/anaconda3/envs/latest_torch/lib/python3.7/site-packages/comet_ml/console.py", line 374, in __exit__
    self.consumer_thread.join(5)
  File "/home/iulialexandra/anaconda3/envs/latest_torch/lib/python3.7/threading.py", line 1048, in join
    self._wait_for_tstate_lock(timeout=max(timeout, 0))
  File "/home/iulialexandra/anaconda3/envs/latest_torch/lib/python3.7/threading.py", line 1060, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
  File "/home/iulialexandra/anaconda3/envs/latest_torch/lib/python3.7/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 15503) is killed by signal: Terminated.

**Comment by dsblank** [comment]
Looks like PyCharm and Comet internals are conflicting. I use pdb often, and never have issues. But I don't use PyCharm.

**Comment by gidim** [comment]
As a temporary solution you can set Disable=True in the experiment object when debugging. This way nothing will be reported to Comet and this error would likely go away

**Comment by dsblank** [comment]
As @gidim mentioned, please try: `Experiment(disabled=True)` when you create an experiment. Let us know if that solves the problem.

**Comment by iulialexandra** [comment]
Unfortunately when I set disabled=True, I get another error, this time even in normal run mode:
AttributeError: 'NoneType' object has no attribute 'put_messge_in_q'.

I tried updating pycharm as well, no change. 

Traceback (most recent call last):
  File "/mnt/Storage/code/incremental/icarl_pytorch/main.py", line 141, in <module>
    main()
  File "/mnt/Storage/code/incremental/icarl_pytorch/main.py", line 68, in main
    weights_to_comet(experiment, icarl, 0, "weights_hist")
  File "/mnt/Storage/code/incremental/icarl_pytorch/utils.py", line 135, in weights_to_comet
    experiment.log_histogram_3d(np.ravel(weights), name=hist_name, step=step)
  File "/home/iulialexandra/anaconda3/envs/latest_torch/lib/python3.7/site-packages/comet_ml/experiment.py", line 1834, in log_histogram_3d
    require_step=True,
  File "/home/iulialexandra/anaconda3/envs/latest_torch/lib/python3.7/site-packages/comet_ml/experiment.py", line 1387, in _log_asset_data
    self.streamer.put_messge_in_q(upload_message)
AttributeError: 'NoneType' object has no attribute 'put_messge_in_q'

**Comment by iulialexandra** [comment]
The original error has been resolved with the latest version of PyCharm (2020.1), I can now debug my code with Comet active. However, the error related to disabled=True still persists.

**Comment by dsblank** [comment]
The error with `disabled=True` should be fixed with comet_ml version 3.1.0 released yesterday. Thanks for letting us know about the PyCharm fix! Let us know if you have any other issues.

**Comment by iulialexandra** [comment]
Awesome, thanks, the other error was also fixed with the new version.
