### ISSUE TITLE
Issue with Keras 2.1.6?

### ISSUE THREAD

**Issue by gaiar** [comet-ml/issue-tracking#34]
```
Traceback (most recent call last):
  File "/home/gaiar/Downloads/pycharm-2018.1.1/helpers/pydev/pydev_run_in_console.py", line 52, in run_file
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/gaiar/Downloads/pycharm-2018.1.1/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/gaiar/PycharmProjects/KerasBirdsClassification/main_squeezenet.py", line 5, in <module>
    from keras.applications.inception_v3 import preprocess_input
  File "/home/gaiar/Downloads/pycharm-2018.1.1/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/gaiar/anaconda3/envs/gpu-nn/lib/python3.6/site-packages/Keras-2.1.6-py3.6.egg/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/home/gaiar/Downloads/pycharm-2018.1.1/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/gaiar/anaconda3/envs/gpu-nn/lib/python3.6/site-packages/Keras-2.1.6-py3.6.egg/keras/utils/__init__.py", line 25, in <module>
    from .multi_gpu_utils import multi_gpu_model
  File "/home/gaiar/Downloads/pycharm-2018.1.1/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/home/gaiar/anaconda3/envs/gpu-nn/lib/python3.6/site-packages/Keras-2.1.6-py3.6.egg/keras/utils/multi_gpu_utils.py", line 11, in <module>
    from ..models import clone_model
  File "/home/gaiar/Downloads/pycharm-2018.1.1/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 20, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/home/gaiar/anaconda3/envs/gpu-nn/lib/python3.6/site-packages/comet_ml/monkey_patching.py", line 36, in exec_module
    self.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 780, in get_code
  File "<frozen importlib._bootstrap_external>", line 832, in get_data
NotADirectoryError: [Errno 20] Not a directory: '/home/gaiar/anaconda3/envs/gpu-nn/lib/python3.6/site-packages/Keras-2.1.6-py3.6.egg/keras/models.py'
```

**Comment by Nimrod007** [comment]
thanks for the update. what is the comet version ?

**Comment by gaiar** [comment]
```
(gpu-nn) gaiar@gaiar-laptop:~$ pip install comet-ml
Requirement already satisfied: comet-ml in ./anaconda3/envs/gpu-nn/lib/python3.6/site-packages (1.0.8)
Requirement already satisfied: wurlitzer>=1.0.1 in ./anaconda3/envs/gpu-nn/lib/python3.6/site-packages (from comet-ml) (1.0.1)
Requirement already satisfied: six in ./anaconda3/envs/gpu-nn/lib/python3.6/site-packages (from comet-ml) (1.11.0)
Requirement already satisfied: requests>=2.18.4 in ./anaconda3/envs/gpu-nn/lib/python3.6/site-packages (from comet-ml) (2.18.4)
Requirement already satisfied: websocket-client>=0.44.0 in ./anaconda3/envs/gpu-nn/lib/python3.6/site-packages (from comet-ml) (0.47.0)
Requirement already satisfied: certifi>=2017.4.17 in ./anaconda3/envs/gpu-nn/lib/python3.6/site-packages (from requests>=2.18.4->comet-ml) (2018.4.16)
Requirement already satisfied: idna<2.7,>=2.5 in ./anaconda3/envs/gpu-nn/lib/python3.6/site-packages (from requests>=2.18.4->comet-ml) (2.6)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in ./anaconda3/envs/gpu-nn/lib/python3.6/site-packages (from requests>=2.18.4->comet-ml) (1.22)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./anaconda3/envs/gpu-nn/lib/python3.6/site-packages (from requests>=2.18.4->comet-ml) (3.0.4)
```

**Comment by corriebar** [comment]
Same problem here:
```
/home/corrie/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Traceback (most recent call last):
  File "keras_example_comet.py", line 8, in <module>
    import keras
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "/home/corrie/anaconda3/lib/python3.6/site-packages/Keras-2.1.5-py3.6.egg/keras/__init__.py", line 5, in <module>
    # You may obtain a copy of the License at
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "/home/corrie/anaconda3/lib/python3.6/site-packages/Keras-2.1.5-py3.6.egg/keras/applications/__init__.py", line 1, in <module>
    # Copyright 2017 Google Inc. All Rights Reserved.
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "/home/corrie/anaconda3/lib/python3.6/site-packages/Keras-2.1.5-py3.6.egg/keras/applications/vgg16.py", line 16, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "/home/corrie/anaconda3/lib/python3.6/site-packages/comet_ml/monkey_patching.py", line 36, in exec_module
    self.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 780, in get_code
  File "<frozen importlib._bootstrap_external>", line 832, in get_data
NotADirectoryError: [Errno 20] Not a directory: '/home/corrie/anaconda3/lib/python3.6/site-packages/Keras-2.1.5-py3.6.egg/keras/models.py'
COMET INFO: Uploading stats to Comet before program termination (may take several seconds)
```

Comet-ML Version:
```
pip install comet-ml                                                      
Requirement already satisfied: comet-ml in /home/corrie/anaconda3/lib/python3.6/site-packages (1.0.11)
Requirement already satisfied: six in /home/corrie/anaconda3/lib/python3.6/site-packages (from comet-ml) (1.11.0)
Requirement already satisfied: wurlitzer>=1.0.1 in /home/corrie/anaconda3/lib/python3.6/site-packages (from comet-ml) (1.0.1)
Requirement already satisfied: websocket-client>=0.44.0 in /home/corrie/anaconda3/lib/python3.6/site-packages (from comet-ml) (0.47.0)
Requirement already satisfied: requests>=2.18.4 in /home/corrie/anaconda3/lib/python3.6/site-packages (from comet-ml) (2.18.4)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/corrie/anaconda3/lib/python3.6/site-packages (from requests>=2.18.4->comet-ml) (3.0.4)
Requirement already satisfied: idna<2.7,>=2.5 in /home/corrie/anaconda3/lib/python3.6/site-packages (from requests>=2.18.4->comet-ml) (2.6)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /home/corrie/anaconda3/lib/python3.6/site-packages (from requests>=2.18.4->comet-ml) (1.22)
Requirement already satisfied: certifi>=2017.4.17 in /home/corrie/anaconda3/lib/python3.6/site-packages (from requests>=2.18.4->comet-ml) (2018.4.16)
redshift-sqlalchemy 0.4 has requirement psycopg2==2.5, but you'll have psycopg2 2.7.4 which is incompatible.
pyopenssl 17.2.0 has requirement cryptography>=1.9, but you'll have cryptography 1.7.2 which is incompatible.
```

**Comment by gidim** [comment]
This is likely to be Anaconda related. We're looking into this. Thanks for reporting!

**Comment by Nimrod007** [comment]
resolved on [![PyPI version](https://badge.fury.io/py/comet-ml.svg)](https://badge.fury.io/py/comet-ml)
