### ISSUE TITLE
comet hides the last two lines of `Traceback` error msg 

### ISSUE THREAD

**Issue by ZENGXH** [comet-ml/issue-tracking#345]
When comet is enabled, the last two lines of Trackback will disappear. It makes debugging code hard. 

To reproduce my issue: 
The `test_comet.py`
```python
from comet_ml import OfflineExperiment as Experiment 
exp = Experiment(project_name="test")
from torch import nn 

opt = nn.optim.Adam() # where the bug is 
```

The output : 
```
>> python test_comet.py
Traceback (most recent call last):
  File "test_comet.py", line 6, in <module>
COMET INFO: Uploading stats to Comet before program termination (may take several seconds)
COMET INFO: Starting saving the offline archive
COMET INFO: To upload this offline experiment, run:
    comet upload /tmp/411125f4ba994108a214481f7c4d183a.zip
```

With the comet exp commented: 
```python
from comet_ml import OfflineExperiment as Experiment 
# exp = Experiment(project_name="test") 
from torch import nn 

opt = nn.optim.Adam() # where the bug is 
```

the output is normal now: 
```
Traceback (most recent call last):
  File "test_comet.py", line 6, in <module>
    opt = nn.optim.Adam() 
AttributeError: module 'torch.nn' has no attribute 'optim'
```

**Comment by dsblank** [comment]
@ZENGXH Thanks for reporting. I think the issue is that comet_ml assumes that you program is working, and anything that prevents normal running is an incompatibility. In your case, you don't have a correct program yet. One workaround (as you have noticed) is don't import comet_ml until you have a working program. Another option would be to set `COMET_LOGGING_CONSOLE` to "debug" as described here: https://www.comet.ml/docs/python-sdk/advanced/#comet-configuration-variables

**Comment by ZENGXH** [comment]
Thanks! It would be nice to if this issue can be fixed. 

Sometimes errors can pop out during the training of the model (say after several hours). And debugging/reproducing the problem may require another run (without importing comet_ml), which is really bad.  

BTW I try set the environment variable, but gets the following message: 

```
COMET DEBUG: Got 1 messages, 0 still in queue                                                                                                                                                                                                                                   COMET DEBUG: Putting 1 <class 'comet_ml.messages.Message'> in queue                                                                                                                                                                                                             COMET DEBUG: Got 1 messages, 0 still in queue                                                                                                                                                                                                                                   COMET DEBUG: Got output for stderr: b"COMET DEBUG: Putting 1 <class 'comet_ml.messages.Message'> in queue\n"                                                                                                                                                                    COMET DEBUG: Putting 1 <class 'comet_ml.messages.Message'> in queue                                                                                                            
COMET DEBUG: Got output for stderr: b'COMET DEBUG: Got output for stderr: b\'COMET DEBUG: Got output for stderr: b"COMET DEBUG: Got output for stderr: b\\\'COMET DEBUG: Got 1 messages, 20 still in queue\\\\\\\\n\\\'\\\\n"\\n\'\n'
COMET DEBUG: Putting 1 <class 'comet_ml.messages.Message'> in queue                                                                                                                                                                                                             
COMET DEBUG: Got output for stderr: b'COMET DEBUG: Got 1 messages, 1 still in queue\n'                                                                                                                                                                                          COMET DEBUG: Got 1 messages, 1 still in queue                                                                                                                                                                                                                                   COMET DEBUG: Putting 1 <class 'comet_ml.messages.Message'> in queue                                                                                                                                                                                                             COMET DEBUG: Got 1 messages, 1 still in queue                                                                                                                                          
COMET DEBUG: Got 1 messages, 0 still in queue                                                                                                           
COMET DEBUG: Got output for stderr: b"COMET DEBUG: Putting 1 <class 'comet_ml.messages.Message'> in queue\n"                                                                                                                                                                    
COMET DEBUG: Git patch is empty, nothing to upload                                                                                                                                                                                                                              COMET DEBUG: Putting 1 <class 'comet_ml.messages.Message'> in queue                                                                                                                                                                                                             
COMET DEBUG: Command line arguments None                                                                                                                                                                                                                                        
COMET DEBUG: Putting 1 <class 'comet_ml.messages.Message'> in queue                                                                                                                                                                                                             
COMET DEBUG: Got 1 messages, 1 still in queue                                                                                                                                  
COMET DEBUG: Got output for stderr: b'COMET DEBUG: Got 1 messages, 0 still in queue\n'                                                                                         
COMET DEBUG: Putting 1 <class 'comet_ml.messages.Message'> in queue                                                                                                           
COMET DEBUG: Got output for stderr: b"COMET DEBUG: Got output for stderr: b'COMET DEBUG: Got 1 messages, 1 still in queue\\n'\n"                        
COMET DEBUG: Putting 1 <class 'comet_ml.messages.Message'> in queue                                                                                                                                                                                                             
COMET DEBUG: Got 1 messages, 2 still in queue                                                                                                                                                                                                                                   
COMET DEBUG: Got 1 messages, 1 still in queue                                                                                                                                                                                                                                   
COMET DEBUG: Got output for stderr: b'COMET DEBUG: Got 1 messages, 0 still in queue\n'                                                                                                                                                                                  
COMET DEBUG: Got 1 messages, 0 still in queue                                                                                                                                                             
COMET DEBUG: Putting 1 <class 'comet_ml.messages.Message'> in queue                                                                                                                                                                                                             
COMET DEBUG: Got 1 messages, 0 still in queue                                                                                                                                                                                                                                   
COMET DEBUG: Got output for stderr: b"COMET DEBUG: Putting 1 <class 'comet_ml.messages.Message'> in queue\n"                                                                                                                                                                    
COMET DEBUG: Putting 1 <class 'comet_ml.messages.Message'> in queue                                                                                                                                                                                                             
COMET DEBUG: Got 1 messages, 0 still in queue                                                                                                                                                                                                                                   
COMET DEBUG: Got output for stderr: b'COMET DEBUG: Got output for stderr: b"COMET DEBUG: Putting 1 <class \'comet_ml.messages.Message\'> in queue\\n"\n'                                                  
COMET DEBUG: Putting 1 <class 'comet_ml.messages.Message'> in queue                                         
COMET DEBUG: Got 1 messages, 0 still in queue                                                                                                                                                                                                                                   
COMET DEBUG: Got output for stderr: b"COMET DEBUG: Putting 1 <class 'comet_ml.messages.Message'> in queue\n"                                            
COMET DEBUG: Putting 1 <class 'comet_ml.messages.Message'> in queue                                                                                                                                       
COMET DEBUG: Got output for stderr: b"COMET DEBUG: Got output for stderr: b'COMET DEBUG: Got 1 messages, 0 still in queue\\n'\n"                        
COMET DEBUG: Got 1 messages, 0 still in queue                                                                                                                                                                                                                                   
COMET DEBUG: Putting 1 <class 'comet_ml.messages.Message'> in queue                                                                                                                                                                                                             
COMET DEBUG: Got 1 messages, 0 still in queue                                                                                                                                                                                                                                   
COMET DEBUG: Got output for stderr: b'COMET DEBUG: Got 1 messages, 1 still in queue\n'                                                                                                                                                                                         
COMET DEBUG: Putting 1 <class 'comet_ml.messages.Message'> in queue                                                                                                                                                                                                             
COMET DEBUG: Got output for stderr: b"COMET DEBUG: Putting 1 <class 'comet_ml.messages.Message'> in queue\n"                                                                                                                                                                    
COMET DEBUG: Putting 1 <class 'comet_ml.messages.Message'> in queue                                                             
COMET DEBUG: Got 1 messages, 1 still in queue                                                                                                                                  
COMET DEBUG: Got 1 messages, 0 still in queue                                                                                                                                                                                                                                   
COMET DEBUG: Got output for stderr: b'COMET DEBUG: Got 1 messages, 0 still in queue\n'                                                                                                                     
COMET DEBUG: Putting 1 <class 'comet_ml.messages.Message'> in queue                                                                                                                                                                                                     
COMET DEBUG: Got 1 messages, 0 still in queue                                                                                                                                  
COMET DEBUG: Got output for stderr: b'COMET DEBUG: Got output for stderr: b"COMET DEBUG: Got output for stderr: b\'COMET DEBUG: Got 1 messages, 34 still in queue\\\\n\'\\n"\n'                                                                                         
COMET DEBUG: Putting 1 <class 'comet_ml.messages.Message'> in queue                                                                                                                                       
COMET DEBUG: Got 1 messages, 0 still in queue                                                                                                           
COMET DEBUG: Got output for stderr: b'COMET DEBUG: Got 1 messages, 0 still in queue\n'                                          
COMET DEBUG: Putting 1 <class 'comet_ml.messages.Message'> in queue                                                                                                            
COMET DEBUG: Got output for stderr: b"COMET DEBUG: Putting 1 <class 'comet_ml.messages.Message'> in queue\n"                                                                                                                                                                    
COMET DEBUG: Putting 1 <class 'comet_ml.messages.Message'> in queue                                                                                                                                                                                           
COMET DEBUG: Got output for stderr: b"COMET DEBUG: Got output for stderr: b'COMET DEBUG: Got 1 messages, 0 still in queue\\n'\n"                                                                                                                                                
COMET DEBUG: Putting 1 <class 'comet_ml.messages.Message'> in queue                                                                                     
COMET DEBUG: Got 1 messages, 2 still in queue                                                                                   
COMET DEBUG: Got output for stderr: b'COMET DEBUG: Got 1 messages, 0 still in queue\n'                                                                                                                                                                                          
COMET DEBUG: Got 1 messages, 1 still in queue                                                                                                                                  
COMET DEBUG: Putting 1 <class 'comet_ml.messages.Message'> in queue                                                                                     
COMET DEBUG: Got 1 messages, 0 still in queue                                                               
COMET DEBUG: Got output for stderr: b"COMET DEBUG: Putting 1 <class 'comet_ml.messages.Message'> in queue\n"                                                                   
COMET DEBUG: Got 1 messages, 0 still in queue                                                                                                                                  
COMET DEBUG: Putting 1 <class 'comet_ml.messages.Message'> in queue                                                                                                            
COMET DEBUG: Got 1 messages, 0 still in queue                                                                                                                                                                                                                           
COMET DEBUG: Got output for stderr: b'COMET DEBUG: Got output for stderr: b"COMET DEBUG: Putting 1 <class \'comet_ml.messages.Message\'> in queue\\n"\n'                       
COMET DEBUG: Putting 1 <class 'comet_ml.messages.Message'> in queue                                                                                     
COMET DEBUG: Got output for stderr: b'COMET DEBUG: Got 1 messages, 0 still in queue\n'  
```

**Comment by dsblank** [comment]
We are looking into this issue; thanks for reporting!

**Comment by dsblank** [comment]
Confirmed as an issue. On our list. Stay tuned for updates.

**Comment by dsblank** [comment]
As a workaround, you might try setting `COMET_LOGGING_CONSOLE=info` See https://www.comet.ml/docs/python-sdk/advanced/#comet-configuration-variables for more information

**Comment by Lothiraldan** [comment]
Hi @ZENGXH, the issue should be fixed with the latest release of the Comet Python SDK 3.1.6 https://pypi.org/project/comet-ml/3.1.6/.

Could you give a try with the new version and let us know if that resolved the issue?

**Comment by ZENGXH** [comment]
works now. Thank you so much! :)
