### ISSUE TITLE
`log_gradient` example in Pytorch (experiment.log_histogram_3d) leads to index out of bounds

### ISSUE THREAD

**Issue by IanQS** [comet-ml/issue-tracking#441]
## Describe the Bug
I'm using the logger from [Histogram-Logging-Pytorch.ipynb](https://colab.research.google.com/drive/1PJ_EoibXEM6Ogjc_YkPbE3v6eMyCznu-?usp=sharing) and I'm logging the gradients of my algorithm. However, I'm running into an issue where after some time, I'll get an "index" issue specifically 

```
def log_gradients(experiment: comet_ml.BaseExperiment, gradmap: Dict, step: int) -> None:
    for k, v in gradmap.items():
        _v = to_numpy(v)
        experiment.log_histogram_3d(_v, name=k, step=step)  # <----
```

## Expected behavior
No error

## Where is the issue?
- [X] Comet Python SDK

## To Reproduce

Not sure how to reproduce, sorry :( I'm not even sure why it happens as it works until it doesn't ? 

## Stack Trace
If possible please include the full stack trace of your issue here

```
Traceback (most recent call last):
  File "runner.py", line 210, in <module>
    log_gradients(ml_logger, gradmap, epoch_i * steps_per_epoch)
  File "/content/trader/trader/utils/pytorch_utils/comet_logging.py", line 38, in log_gradients
    experiment.log_histogram_3d(_v, name=k, step=step)
  File "/usr/local/lib/python3.7/dist-packages/comet_ml/experiment.py", line 2861, in log_histogram_3d
    histogram.add(values)
  File "/usr/local/lib/python3.7/dist-packages/comet_ml/utils.py", line 964, in add
    self._add_via_numpy(values, counts)
  File "/usr/local/lib/python3.7/dist-packages/comet_ml/utils.py", line 929, in _add_via_numpy
    numpy.add.at(self.counts, negative_indices, 1)
IndexError: index 1556 is out of bounds for axis 0 with size 1551
```

## Comet Debug Log
I can run it in debug mode but it SOUNDS like the problem isn't there but in how some of the code is written? I'm not sure

**Comment by IanQS** [comment]
NVM, I misunderstood how to use it. I ended up accumulating the gradients through ALL epoch runs as opposed to resetting it on every new epoch
