### ISSUE TITLE
experiment.log_figure() - File could not be uploaded 

### ISSUE THREAD

**Issue by Nimrod007** [comet-ml/issue-tracking#46]
getting error in sdk:
```
COMET ERROR: File could not be uploaded
Traceback (most recent call last):
  File "/anaconda/lib/python3.6/site-packages/comet_ml/file_uploader.py", line 220, in upload_file
    additional_params,
  File "/anaconda/lib/python3.6/site-packages/comet_ml/file_uploader.py", line 122, in send_file
    _send_file(post_endpoint, params=params, files=files)
  File "/anaconda/lib/python3.6/site-packages/comet_ml/file_uploader.py", line 107, in _send_file
    raise ValueError("POSTing file failed: %s" % r.content)
ValueError: POSTing file failed: b'<html>\r\n<head><title>413 Request Entity Too Large</title></head>\r\n<body bgcolor="white">\r\n<center><h1>413 Request Entity Too Large</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n'
```

**Comment by neighthan** [comment]
Okay, I've gotten this down to a small example that will reproduce the errors I'm getting:

```
import matplotlib
matplotlib.use('Agg')
import seaborn as sns
import numpy as np
import os
from comet_ml import Experiment

# load your key however you prefer
with open(f"{os.environ['HOME']}/.comet_key") as f:
        comet_key = f.read().strip()

experiment = Experiment(comet_key)

fig = sns.jointplot(np.array([1,2,3]), np.array([1,2,3]))

experiment.log_figure('test_fig', fig)
```

This gives me the following output (both the warning about the inability to save the figure and the mistaken detection that I'm running this from a notebook (which appears to come from importing `seaborn`)):

```
COMET WARNING: We detected that you are running inside a Ipython/Jupyter notebook environment but we cannot save your notebook source code. Please be sure to have installed comet_ml as a notebook server extension by running:
jupyter comet_ml enable
COMET WARNING: Comet.ml support for Ipython Notebook is limited at the moment, automatic monitoring andstdout capturing is deactivated
COMET INFO: Experiment is live on comet.ml https://www.comet.ml/...
COMET WARNING: Failing to save the matplotlib figure
COMET INFO: Uploading stats to Comet before program termination (may take several seconds)
COMET INFO: Experiment is live on comet.ml: https://www.comet.ml/...
```

I haven't yet been able to reproduce the `File could not be uploaded` error with a small example.

**Comment by neighthan** [comment]
It seems like not explicitly passing in a figure to `.log_figure` gets rid of the `Failing to save...` warning above.
