### ISSUE TITLE
Failed to check backend version - Run will not be logged

### ISSUE THREAD

**Issue by saidwivedi** [comet-ml/issue-tracking#466]
## Describe the Bug
I am using Comet (3.28.0) with Pytorch Lightning (1.5,1). in Miniconda environment While submitting a job in cluster (which has internet access), the run does not get logged. It shows the following error. This happens randomly.
`COMET WARNING: Failed to check backend version at URL: 'https://www.comet-ml.com/clientlib/isAlive/ver'
COMET ERROR: Run will not be logged`

## Expected behavior
The run should be logged.

## Where is the issue?
- [x] Comet Python SDK
- [ ] Comet UI
- [ ] Third Party Integrations (Huggingface, TensorboardX, Pytorch Lighting etc)

## To Reproduce
This happens randomly.

## Stack Trace
```
COMET WARNING: Failed to check backend version at URL: 'https://www.comet-ml.com/clientlib/isAlive/ver'
COMET ERROR: Run will not be logged
For more details, please refer to: https://www.comet.ml/docs/python-sdk/warnings-errors/
Traceback (most recent call last):
  File "/is/cluster/sdwivedi/miniconda3/envs/poco_cls/lib/python3.8/site-packages/urllib3/connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "/is/cluster/sdwivedi/miniconda3/envs/poco_cls/lib/python3.8/site-packages/urllib3/connectionpool.py", line 994, in _prepare_proxy
    conn.connect()
  File "/is/cluster/sdwivedi/miniconda3/envs/poco_cls/lib/python3.8/site-packages/urllib3/connection.py", line 371, in connect
    self._tunnel()
  File "/is/cluster/sdwivedi/miniconda3/envs/poco_cls/lib/python3.8/http/client.py", line 901, in _tunnel
    (version, code, message) = response._read_status()
  File "/is/cluster/sdwivedi/miniconda3/envs/poco_cls/lib/python3.8/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/is/cluster/sdwivedi/miniconda3/envs/poco_cls/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/is/cluster/sdwivedi/miniconda3/envs/poco_cls/lib/python3.8/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/is/cluster/sdwivedi/miniconda3/envs/poco_cls/lib/python3.8/site-packages/urllib3/connectionpool.py", line 813, in urlopen
    return self.urlopen(
  File "/is/cluster/sdwivedi/miniconda3/envs/poco_cls/lib/python3.8/site-packages/urllib3/connectionpool.py", line 813, in urlopen
    return self.urlopen(
  File "/is/cluster/sdwivedi/miniconda3/envs/poco_cls/lib/python3.8/site-packages/urllib3/connectionpool.py", line 813, in urlopen
    return self.urlopen(
  File "/is/cluster/sdwivedi/miniconda3/envs/poco_cls/lib/python3.8/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/is/cluster/sdwivedi/miniconda3/envs/poco_cls/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.comet-ml.com', port=443): Max retries exceeded with url: /clientlib/logger/add/run (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/is/cluster/sdwivedi/miniconda3/envs/poco_cls/lib/python3.8/site-packages/comet_ml/experiment.py", line 865, in _start
    self.alive = self._setup_streamer()
  File "/is/cluster/sdwivedi/miniconda3/envs/poco_cls/lib/python3.8/site-packages/comet_ml/_online.py", line 282, in _setup_streamer
    results = self._authenticate()
  File "/is/cluster/sdwivedi/miniconda3/envs/poco_cls/lib/python3.8/site-packages/comet_ml/_online.py", line 331, in _authenticate
    run_id_response = self.connection.get_run_id(
  File "/is/cluster/sdwivedi/miniconda3/envs/poco_cls/lib/python3.8/site-packages/comet_ml/connection.py", line 574, in get_run_id
    r = self._low_level_http_client.post(
  File "/is/cluster/sdwivedi/miniconda3/envs/poco_cls/lib/python3.8/site-packages/comet_ml/connection.py", line 435, in post
    response = session.post(
  File "/is/cluster/sdwivedi/miniconda3/envs/poco_cls/lib/python3.8/site-packages/requests/sessions.py", line 577, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/is/cluster/sdwivedi/miniconda3/envs/poco_cls/lib/python3.8/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/is/cluster/sdwivedi/miniconda3/envs/poco_cls/lib/python3.8/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/is/cluster/sdwivedi/miniconda3/envs/poco_cls/lib/python3.8/site-packages/requests/adapters.py", line 513, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='www.comet-ml.com', port=443): Max retries exceeded with url: /clientlib/logger/add/run (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out')))
```

**Comment by DN6** [comment]
Hello @saidwivedi. Could you run the following command on your machine and attach the resulting log file here please? 

```
comet check --debug > debug.log
```

**Comment by saidwivedi** [comment]
Below is the dump with `comet check --debug`
```
COMET INFO: Comet Check
COMET INFO: ================================================================================
COMET INFO: Checking connectivity to server...
COMET DEBUG: Unknown env class None
COMET INFO: Configured server address 'https://www.comet-ml.com/clientlib/'
COMET INFO: Server address is the default one
COMET INFO: Server connection is ok
COMET INFO: ================================================================================
COMET INFO: Checking connectivity to Rest API...
COMET INFO: ================================================================================
COMET INFO: Configured Rest API address 'https://www.comet-ml.com/api/rest/v2/'
COMET INFO: Rest API address is the default one
COMET INFO: REST API connection is ok
COMET INFO: ================================================================================
COMET INFO: Checking connectivity to Websocket Server
COMET INFO: ================================================================================
COMET WARNING: No WS address configured on client side, fallback on default WS address 'wss://www.comet-ml.com/ws/logger-ws', if that's incorrect set the WS url through the `comet.ws_url_override` config key
COMET INFO: Configured WS address 'wss://www.comet-ml.com/ws/logger-ws'
COMET DEBUG: Using WS PROXY: proxy:8080
Connecting proxy...
--- request header ---
CONNECT www.comet-ml.com:443 HTTP/1.1
Host: www.comet-ml.com:443


-----------------------
--- response header ---
HTTP/1.1 200 Connection established
-----------------------
--- request header ---
GET /ws/logger-ws HTTP/1.1
Upgrade: websocket
Host: www.comet-ml.com
Origin: https://www.comet-ml.com
Sec-WebSocket-Key: zEYzlBFuZ9e6ZMGs87NDzQ==
Sec-WebSocket-Version: 13
Connection: Upgrade


-----------------------
--- response header ---
HTTP/1.1 101 Switching Protocols
Date: Mon, 28 Mar 2022 14:33:55 GMT
Connection: upgrade
Set-Cookie: AWSALB=Q9lnzTpd2ScqUyieqmNwUuNZMFs++q3IdLwftTAtCqWcR6NHTRQX+9JDQXeYclL6TUdYAhkXNkv9YL5LcsnE6pw4LY32AKohNkrbmQDDZrDtBjK4mnEjEbbhjJzT; Expires=Mon, 04 Apr 2022 14:33:55 GMT; Path=/
Set-Cookie: AWSALBCORS=Q9lnzTpd2ScqUyieqmNwUuNZMFs++q3IdLwftTAtCqWcR6NHTRQX+9JDQXeYclL6TUdYAhkXNkv9YL5LcsnE6pw4LY32AKohNkrbmQDDZrDtBjK4mnEjEbbhjJzT; Expires=Mon, 04 Apr 2022 14:33:55 GMT; Path=/; SameSite=None; Secure
Server: nginx
Sec-WebSocket-Accept: cxaTwpq3g4QL8GL3Bs1fA9KUfFk=
Upgrade: WebSocket
-----------------------
++Sent raw: b'\x81\x84\xf1\x06\xd4\x83\x85c\xa7\xf7'
++Sent decoded: fin=1 opcode=1 data=b'test'
++Rcv raw: b'\x81\x10remote logger on'
++Rcv decoded: fin=1 opcode=1 data=b'remote logger on'
++Sent raw: b'\x88\x82Y\x08\xa3\x1eZ\xe0'
++Sent decoded: fin=1 opcode=8 data=b'\x03\xe8'
COMET INFO: Websocket connection is ok
COMET INFO: ================================================================================
COMET INFO: Checking connectivity to Optimizer Server
COMET INFO: ================================================================================
COMET DEBUG: Unknown env class None
COMET INFO: Configured Optimizer address 'https://www.comet-ml.com/optimizer/'
COMET INFO: Optimizer address is the default one
COMET INFO: Optimizer connection is ok
COMET INFO: ================================================================================
COMET INFO: System Information
COMET INFO: ================================================================================
COMET INFO: Python 3.8.12 (default, Oct 12 2021, 13:49:34)
[GCC 7.5.0] on linux
/home/sdwivedi/miniconda3/envs/poco_cls/bin/python
COMET INFO: requests	v2.27.1
COMET INFO: urllib3	v1.26.8
COMET INFO: websocket	v1.3.1
COMET INFO: --------------------------------------------------------------------------------
COMET INFO: System Proxies Information
COMET INFO: --------------------------------------------------------------------------------
COMET INFO: https: http://proxy:8080
COMET INFO: http: http://proxy:8080
COMET INFO: --------------------------------------------------------------------------------
COMET INFO: https://www.comet-ml.com/clientlib/ -> http://proxy:8080
COMET INFO: https://www.comet-ml.com/api/rest/v2/ -> http://proxy:8080
COMET INFO: wss://www.comet-ml.com/ws/logger-ws -> http://proxy:8080
COMET INFO: --------------------------------------------------------------------------------
COMET INFO: TLS Certificate verification is ENABLED
COMET INFO: ================================================================================
COMET INFO: HTTP CA bundle paths
COMET INFO: --------------------------------------------------------------------------------
COMET INFO: requests is using the default CA bundle
COMET INFO: Summary
COMET INFO: --------------------------------------------------------------------------------
COMET INFO: Server connectivity			True
COMET INFO: Rest API connectivity		True
COMET INFO: WS server connectivity		True
COMET INFO: Optimizer server connectivity	True
```

**Comment by saidwivedi** [comment]
No I am not uploading any files as asset. I am using Pytorch Lightning (1.51.1) which logs standard loss metrics by calling `log_metrics` internally and use `log_histogram_3d` explicitly in the code.

More details - `COMET ERROR: File-like could not be uploaded` occurs at random time in different experiment. Once it hits the error, the experiment doesn't log anything after some time even though I see 'run' symbol in the dashboard. I will run the experiment with debug mode and paste the results here
