### ISSUE TITLE
Error with keras: `TypeError: can't pickle _thread.RLock objects`

### ISSUE THREAD

**Issue by gidim** [comet-ml/issue-tracking#50]
```Traceback (most recent call last):
  File "/Users/caanderson/Documents/repos/datascience-product-pageseg-maskrcnn/samples/nucleus/nucleus.py", line 500, in <module>
    train(model, args.dataset, args.subset)
  File "/Users/caanderson/Documents/repos/datascience-product-pageseg-maskrcnn/samples/nucleus/nucleus.py", line 294, in train
    layers='heads')
  File "/Users/caanderson/Documents/repos/datascience-product-pageseg-maskrcnn/mrcnn/model.py", line 2328, in train
    use_multiprocessing=False,
  File "/Users/caanderson/anaconda/envs/maskrcnn/lib/python3.6/site-packages/comet_ml/keras_logger.py", line 37, in wrapper
    return real_fit(*args, **kwargs)
  File "/Users/caanderson/anaconda/envs/maskrcnn/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/Users/caanderson/anaconda/envs/maskrcnn/lib/python3.6/site-packages/keras/engine/training.py", line 2141, in fit_generator
    callbacks.on_train_begin()
  File "/Users/caanderson/anaconda/envs/maskrcnn/lib/python3.6/site-packages/keras/callbacks.py", line 130, in on_train_begin
    callback.on_train_begin(logs)
  File "/Users/caanderson/anaconda/envs/maskrcnn/lib/python3.6/site-packages/comet_ml/frameworks.py", line 109, in on_train_begin
    self.experiment.set_model_graph(get_keras_json_model(self.model))
  File "/Users/caanderson/anaconda/envs/maskrcnn/lib/python3.6/site-packages/comet_ml/frameworks.py", line 134, in get_keras_json_model
    return model.to_json()
  File "/Users/caanderson/anaconda/envs/maskrcnn/lib/python3.6/site-packages/keras/engine/topology.py", line 2710, in to_json
    model_config = self._updated_config()
  File "/Users/caanderson/anaconda/envs/maskrcnn/lib/python3.6/site-packages/keras/engine/topology.py", line 2677, in _updated_config
    config = self.get_config()
  File "/Users/caanderson/anaconda/envs/maskrcnn/lib/python3.6/site-packages/keras/engine/topology.py", line 2432, in get_config
    return copy.deepcopy(config)
  File "/Users/caanderson/anaconda/envs/maskrcnn/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/Users/caanderson/anaconda/envs/maskrcnn/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/Users/caanderson/anaconda/envs/maskrcnn/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/Users/caanderson/anaconda/envs/maskrcnn/lib/python3.6/copy.py", line 215, in _deepcopy_list
    append(deepcopy(a, memo))
  File "/Users/caanderson/anaconda/envs/maskrcnn/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/Users/caanderson/anaconda/envs/maskrcnn/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/Users/caanderson/anaconda/envs/maskrcnn/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/Users/caanderson/anaconda/envs/maskrcnn/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/Users/caanderson/anaconda/envs/maskrcnn/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/Users/caanderson/anaconda/envs/maskrcnn/lib/python3.6/copy.py", line 220, in _deepcopy_tuple
    y = [deepcopy(a, memo) for a in x]
  File "/Users/caanderson/anaconda/envs/maskrcnn/lib/python3.6/copy.py", line 220, in <listcomp>
    y = [deepcopy(a, memo) for a in x]
  File "/Users/caanderson/anaconda/envs/maskrcnn/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/Users/caanderson/anaconda/envs/maskrcnn/lib/python3.6/copy.py", line 220, in _deepcopy_tuple
    y = [deepcopy(a, memo) for a in x]
  File "/Users/caanderson/anaconda/envs/maskrcnn/lib/python3.6/copy.py", line 220, in <listcomp>
    y = [deepcopy(a, memo) for a in x]
  File "/Users/caanderson/anaconda/envs/maskrcnn/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/Users/caanderson/anaconda/envs/maskrcnn/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/Users/caanderson/anaconda/envs/maskrcnn/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/Users/caanderson/anaconda/envs/maskrcnn/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/Users/caanderson/anaconda/envs/maskrcnn/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/Users/caanderson/anaconda/envs/maskrcnn/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/Users/caanderson/anaconda/envs/maskrcnn/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/Users/caanderson/anaconda/envs/maskrcnn/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/Users/caanderson/anaconda/envs/maskrcnn/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/Users/caanderson/anaconda/envs/maskrcnn/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/Users/caanderson/anaconda/envs/maskrcnn/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/Users/caanderson/anaconda/envs/maskrcnn/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/Users/caanderson/anaconda/envs/maskrcnn/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/Users/caanderson/anaconda/envs/maskrcnn/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/Users/caanderson/anaconda/envs/maskrcnn/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/Users/caanderson/anaconda/envs/maskrcnn/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/Users/caanderson/anaconda/envs/maskrcnn/lib/python3.6/copy.py", line 169, in deepcopy
    rv = reductor(4)
TypeError: can't pickle _thread.RLock objects```

using Comet with this  keras/tensorflow model and finding it causes training to crash with the message above. https://github.com/matterport/Mask_RCNN. All is well as long as I leave comet out of it. I can reproduce the problem on the "nucleus" sample dataset and script in this repo.

**Comment by gidim** [comment]
This is an issue with keras `model.to_json()` call. 
Reported here:
https://github.com/keras-team/keras/issues/8343

We'll catch this TypeError and throw a warning instead to not fail training.
