### ISSUE TITLE
[LangChain] Error using CometCallbackHandler with AgentExecutor

### ISSUE THREAD

**Issue by bmanturner** [comet-ml/issue-tracking#515]
```
COMET ERROR: Failed to export agent or LLM to Comet
Traceback (most recent call last):
  File "/Users/bfturner/dev/heavynl/venv/lib/python3.10/site-packages/langchain/callbacks/comet_ml_callback.py", line 484, in _log_model
    langchain_asset.save(langchain_asset_path)
  File "/Users/bfturner/dev/heavynl/venv/lib/python3.10/site-packages/langchain/agents/agent.py", line 591, in save
    raise ValueError(
ValueError: Saving not supported for agent executors. If you are trying to save the agent, please use the `.save_agent(...)`
```

**Comment by omarsar** [comment]
Running into the same issue!

**Comment by Lothiraldan** [comment]
Hello @bmanturner @omarsar, we worked with the langchain maintainers to solve a couple of issue related to serialization. Could you try again with the latest version of langchain?

**Comment by dsblank** [comment]
This issue is being closed due to its staleness. Please reopen if further issue. Thanks!
