### ISSUE TITLE
Comet crashes with pytorch and run:ai

### ISSUE THREAD

**Issue by R-Peleg** [comet-ml/issue-tracking#519]
## Describe the Bug
Running an experiment with Comet, as a part of RunAI container of PyTorch application, crashed right at the beginning.

## Expected behavior
The program should run

## Where is the issue?
- Comet Python SDK

## To Reproduce
1. Create a project using Comet with PyTorch
2. Run it by using runai-submit

## Stack Trace
If possible please include the full stack trace of your issue here

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x148 pc=0x17d6f70]

goroutine 1 [running]:
github.com/run-ai/runai-operator/researcher-service/runai-cli/cmd/logs.NewLogsCommand.func1(0xc00033ac80?, {0xc000549a90?, 0x1?, 0x1?})
	/home/runner/work/runai-operator/runai-operator/researcher-service/runai-cli/cmd/logs/logs.go:89 +0x570
github.com/spf13/cobra.(*Command).execute(0xc00033ac80, {0xc000549a60, 0x1, 0x1})
	/home/runner/work/runai-operator/runai-operator/researcher-service/runai-cli/vendor/github.com/spf13/cobra/command.go:876 +0x67b
github.com/spf13/cobra.(*Command).ExecuteC(0xc000161400)
	/home/runner/work/runai-operator/runai-operator/researcher-service/runai-cli/vendor/github.com/spf13/cobra/command.go:990 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/work/runai-operator/runai-operator/researcher-service/runai-cli/vendor/github.com/spf13/cobra/command.go:918
main.main()
	/home/runner/work/runai-operator/runai-operator/researcher-service/runai-cli/cmd/main/main.go:61 +0xcf
```

## Comet Debug Log
I have the file, but can't post it publicly.

## Screenshots or GIFs
Not applicable.

## Link to Comet Project/Experiment
Not applicable.

## Additional context
It does not happen all of the time. Approximately once every 3-4 runs I get this.

**Comment by R-Peleg** [comment]
My bad, it was RunAI issue. Closing.
