### ISSUE TITLE
Logging conda environment

### ISSUE THREAD

**Issue by mhnazeri** [comet-ml/issue-tracking#530]
## Describe the Bug
I use [micromamba](https://mamba.readthedocs.io/en/latest/installation/micromamba-installation.html) instead of conda. Comet recognizes the environment as a conda environment and starts logging it, but it's not there. So, it throws a warning each time.

## Expected behavior
Do not recognize micromamba as conda or have a switch to turn off the logging of conda environment. I couldn't find any information on this in the docs.

## To Reproduce
1. Install [micromamba](https://mamba.readthedocs.io/en/latest/installation/micromamba-installation.html)
2. Run an experiment inside micromamba
3. See warning

```
COMET WARNING: Unknown error exporting current conda environment
Traceback (most recent call last):
  File "/opt/micromamba/envs/torch/lib/python3.11/site-packages/comet_ml/utils.py", line 690, in subprocess_run_and_check
    completed_process = subprocess_run(args, timeout=timeout)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/micromamba/envs/torch/lib/python3.11/site-packages/comet_ml/compat_utils.py", line 108, in subprocess_run
    return subprocess.run(
           ^^^^^^^^^^^^^^^
  File "/opt/micromamba/envs/torch/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/micromamba/envs/torch/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/micromamba/envs/torch/lib/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileN

FileNotFoundError: [Errno 2] No such file or directory: 'conda'


COMET WARNING: Unknown error retrieving Conda package as an explicit file
Traceback (most recent call last):
  File "/opt/micromamba/envs/torch/lib/python3.11/site-packages/comet_ml/utils.py", line 690, in subprocess_run_and_check
    completed_process = subprocess_run(args, timeout=timeout)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/micromamba/envs/torch/lib/python3.11/site-packages/comet_ml/compat_utils.py", line 108, in subprocess_run
    return subprocess.run(
           ^^^^^^^^^^^^^^^
  File "/opt/micromamba/envs/torch/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/micromamba/envs/torch/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/micromamba/envs/torch/lib/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filena

me)
FileNotFoundError: [Errno 2] No such file or directory: 'conda'


COMET WARNING: Unknown error retrieving Conda information
Traceback (most recent call last):
  File "/opt/micromamba/envs/torch/lib/python3.11/site-packages/comet_ml/utils.py", line 690, in subprocess_run_and_check
    completed_process = subprocess_run(args, timeout=timeout)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/micromamba/envs/torch/lib/python3.11/site-packages/comet_ml/compat_utils.py", line 108, in subprocess_run
    return subprocess.run(
           ^^^^^^^^^^^^^^^
  File "/opt/micromamba/envs/torch/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/micromamba/envs/torch/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/micromamba/envs/torch/lib/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFound

Error: [Errno 2] No such file or directory: 'conda'
```

Thank you in advance.

**Comment by dsblank** [comment]
If you set `log_env_details` to False, then it won't log any of the env, including the conda packages. We're working on allowing better control of logging, but for now that is the only way to turn it off. Otherwise, you could try putting a conda folder (and maybe other files) to avoid the error. We'll add support for micromamba to our list. Thanks for reporting.

```python
experiment = Experiment(log_env_details=False)
```

**Comment by mhnazeri** [comment]
Ah, I see. My bad. Thanks, that worked.
