### ISSUE TITLE
COMET ERROR: Error sending parameters batch (online experiment). OperationalError: database or disk is full

### ISSUE THREAD

**Issue by kirilllzaitsev** [comet-ml/issue-tracking#553]
## Before Asking:   
- [+] I have searched the Issue Tracker.   
- [+] I have searched the Documentation.    

## What is your question related to?
- [+] Comet Python SDK
- [ ] Comet UI
- [ ] Third Party Integrations (Huggingface, TensorboardX, Pytorch Lightning etc.)  

## What is your question?

I would like to know the causes and troubleshooting steps for the error `COMET ERROR: Error sending parameters batch (online experiment). OperationalError: database or disk is full`

Here is some context:

```
Exception in thread Thread-69:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/user/venv/lib/python3.10/site-packages/comet_ml/comet.py", line 221, in run
    out = self._loop()
  File "/home/user/venv/lib/python3.10/site-packages/comet_ml/comet.py", line 1539, in _loop
    self._process_queue_messages(messages)
  File "/home/user/venv/lib/python3.10/site-packages/comet_ml/comet.py", line 1576, in _process_queue_messages
    self.replay_manager.register_messages(messages, status=status)
  File "/home/user/venv/lib/python3.10/site-packages/comet_ml/replay_manager.py", line 166, in register_messages
    self.conn.executemany("INSERT INTO messages VALUES (?,?,?,?)", values)
sqlite3.OperationalError: database or disk is full


  0%|          | 34/8005 [00:01<05:55, 22.41it/s][A

  0%|          | 34/8005 [00:01<06:48, 19.54it/s][A

  1%|          | 68/8005 [00:02<05:39, 23.37it/s][A

  1%|          | 68/8005 [00:03<05:51, 22.59it/s][A

  1%|▏         | 102/8005 [00:04<06:01, 21.86it/s][A

  1%|▏         | 102/8005 [00:04<06:11, 21.28it/s][A

  2%|▏         | 136/8005 [00:05<05:38, 23.26it/s][A

  2%|▏         | 136/8005 [00:06<05:42, 22.99it/s][A

  2%|▏         | 170/8005 [00:07<05:57, 21.93it/s][A

  2%|▏         | 170/8005 [00:07<05:58, 21.86it/s][ACOMET ERROR: Error sending stdout/stderr batch (online experiment). OperationalError: database or disk is full
```

**Comment by dsblank** [comment]
@kirilllzaitsev it looks like your disk is full. You could turn off logging of standard out:

```python
experiment = comet_ml.Experiment(auto_output_logging=None)
```

**Comment by dsblank** [comment]
@kirilllzaitsev, yes it goes to an intermediate database. I believe it is a SQLite database. I'm not sure of the location. But it shouldn't matter.

There is a lot of engineering to fallback to offline, but it doesn't work if you don't have the disk space. Does that help?

**Comment by kirilllzaitsev** [comment]
Yes, thank you, the reason for the problem is clear
