### ISSUE TITLE
Cannot allocate memory Error

### ISSUE THREAD

**Issue by jhonatanoliveira** [comet-ml/issue-tracking#93]
A _cannot allocate memory_ error message appeared for the first time while calling `log_image`.
I am running the code in Floydhub (docker environment) with tensorflow 1.8.

Follows the traceback:

```
Traceback (most recent call last):
File "[...]", line 394, in <module>
experiment.log_image("{}/{}.png".format(save_imgs_path, img_idx))
File "/usr/local/lib/python3.6/site-packages/comet_ml/__init__.py", line 767, in log_image
url_params,
File "/usr/local/lib/python3.6/site-packages/comet_ml/file_uploader.py", line 205, in upload_file_contents_process
p.start()
File "/usr/local/lib/python3.6/multiprocessing/process.py", line 105, in start
self._popen = self._Popen(self)
File "/usr/local/lib/python3.6/multiprocessing/context.py", line 223, in _Popen
return _default_context.get_context().Process._Popen(process_obj)
File "/usr/local/lib/python3.6/multiprocessing/context.py", line 277, in _Popen
return Popen(process_obj)
File "/usr/local/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
self._launch(process_obj)
File "/usr/local/lib/python3.6/multiprocessing/popen_fork.py", line 66, in _launch
self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
COMET INFO: Uploading stats to Comet before program termination (may take several seconds)
COMET INFO: Experiment is live on comet.ml [...]
```

**Comment by ceceshao1** [comment]
@jhonatanoliveira - what's the size of the image you're trying to upload?

**Comment by jhonatanoliveira** [comment]
@ceceshao1 It's a sequence of 50 images with size 2.8 KB on average.
I've done this same process many times before (and after) this error. I am not sure what triggered it in this special run.

**Comment by Nimrod007** [comment]
Hey @jhonatanoliveira - thanks for reporting this. Ive ran a similar example and didn't encounter this error. if the problem is the problem still reproducing on your side ?

Thanks

**Comment by jhonatanoliveira** [comment]
Hello @Nimrod007 
The problem didn't happen again and I can't reproduce it anymore. I'll assume it was a one-time thing. If it happens again I'll re-open the issue. Thanks.
